// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type of broadcast message
type MessageType int32

const (
	MessageType_BID   MessageType = 0
	MessageType_JOIN  MessageType = 1
	MessageType_LEAVE MessageType = 2
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "BID",
		1: "JOIN",
		2: "LEAVE",
	}
	MessageType_value = map[string]int32{
		"BID":   0,
		"JOIN":  1,
		"LEAVE": 2,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{0}
}

// Replication:
type ReplicateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bidder        string                 `protobuf:"bytes,1,opt,name=bidder,proto3" json:"bidder,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateRequest) Reset() {
	*x = ReplicateRequest{}
	mi := &file_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateRequest) ProtoMessage() {}

func (x *ReplicateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateRequest.ProtoReflect.Descriptor instead.
func (*ReplicateRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{0}
}

func (x *ReplicateRequest) GetBidder() string {
	if x != nil {
		return x.Bidder
	}
	return ""
}

func (x *ReplicateRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ReplicateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateResponse) Reset() {
	*x = ReplicateResponse{}
	mi := &file_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateResponse) ProtoMessage() {}

func (x *ReplicateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateResponse.ProtoReflect.Descriptor instead.
func (*ReplicateResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{1}
}

func (x *ReplicateResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// Request message when a client joins
type JoinRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ParticipantName string                 `protobuf:"bytes,1,opt,name=participant_name,json=participantName,proto3" json:"participant_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{2}
}

func (x *JoinRequest) GetParticipantName() string {
	if x != nil {
		return x.ParticipantName
	}
	return ""
}

// Message for publishing a bid
type BidMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ParticipantName string                 `protobuf:"bytes,1,opt,name=participant_name,json=participantName,proto3" json:"participant_name,omitempty"`
	Amount          int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BidMessage) Reset() {
	*x = BidMessage{}
	mi := &file_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidMessage) ProtoMessage() {}

func (x *BidMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidMessage.ProtoReflect.Descriptor instead.
func (*BidMessage) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{3}
}

func (x *BidMessage) GetParticipantName() string {
	if x != nil {
		return x.ParticipantName
	}
	return ""
}

func (x *BidMessage) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Response after publishing a bid
type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{4}
}

func (x *PublishResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublishResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Request message when a client leaves
type LeaveRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ParticipantName string                 `protobuf:"bytes,1,opt,name=participant_name,json=participantName,proto3" json:"participant_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LeaveRequest) Reset() {
	*x = LeaveRequest{}
	mi := &file_proto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRequest) ProtoMessage() {}

func (x *LeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRequest.ProtoReflect.Descriptor instead.
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{5}
}

func (x *LeaveRequest) GetParticipantName() string {
	if x != nil {
		return x.ParticipantName
	}
	return ""
}

// Response after leaving
type LeaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveResponse) Reset() {
	*x = LeaveResponse{}
	mi := &file_proto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveResponse) ProtoMessage() {}

func (x *LeaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveResponse.ProtoReflect.Descriptor instead.
func (*LeaveResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{6}
}

func (x *LeaveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Broadcast message sent to all clients
type BroadcastMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Type          MessageType            `protobuf:"varint,3,opt,name=type,proto3,enum=MessageType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastMessage) Reset() {
	*x = BroadcastMessage{}
	mi := &file_proto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastMessage) ProtoMessage() {}

func (x *BroadcastMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastMessage.ProtoReflect.Descriptor instead.
func (*BroadcastMessage) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{7}
}

func (x *BroadcastMessage) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BroadcastMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_BID
}

// Request to get highest bid
type GetHighestBidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHighestBidRequest) Reset() {
	*x = GetHighestBidRequest{}
	mi := &file_proto_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHighestBidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHighestBidRequest) ProtoMessage() {}

func (x *GetHighestBidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHighestBidRequest.ProtoReflect.Descriptor instead.
func (*GetHighestBidRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{8}
}

// Getting highest bid
type GetHighestBidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHighestBidResponse) Reset() {
	*x = GetHighestBidResponse{}
	mi := &file_proto_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHighestBidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHighestBidResponse) ProtoMessage() {}

func (x *GetHighestBidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHighestBidResponse.ProtoReflect.Descriptor instead.
func (*GetHighestBidResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{9}
}

func (x *GetHighestBidResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Request to get if ended bid
type GetIsEndedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIsEndedRequest) Reset() {
	*x = GetIsEndedRequest{}
	mi := &file_proto_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIsEndedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIsEndedRequest) ProtoMessage() {}

func (x *GetIsEndedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIsEndedRequest.ProtoReflect.Descriptor instead.
func (*GetIsEndedRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{10}
}

// Getting if ended bid
type GetIsEndedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        bool                   `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIsEndedResponse) Reset() {
	*x = GetIsEndedResponse{}
	mi := &file_proto_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIsEndedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIsEndedResponse) ProtoMessage() {}

func (x *GetIsEndedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIsEndedResponse.ProtoReflect.Descriptor instead.
func (*GetIsEndedResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{11}
}

func (x *GetIsEndedResponse) GetAmount() bool {
	if x != nil {
		return x.Amount
	}
	return false
}

var File_proto_proto protoreflect.FileDescriptor

const file_proto_proto_rawDesc = "" +
	"\n" +
	"\vproto.proto\"B\n" +
	"\x10ReplicateRequest\x12\x16\n" +
	"\x06bidder\x18\x01 \x01(\tR\x06bidder\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"#\n" +
	"\x11ReplicateResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"8\n" +
	"\vjoinRequest\x12)\n" +
	"\x10participant_name\x18\x01 \x01(\tR\x0fparticipantName\"O\n" +
	"\n" +
	"bidMessage\x12)\n" +
	"\x10participant_name\x18\x01 \x01(\tR\x0fparticipantName\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"C\n" +
	"\x0fpublishResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"9\n" +
	"\fleaveRequest\x12)\n" +
	"\x10participant_name\x18\x01 \x01(\tR\x0fparticipantName\")\n" +
	"\rleaveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"L\n" +
	"\x10broadcastMessage\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12 \n" +
	"\x04type\x18\x03 \x01(\x0e2\f.messageTypeR\x04type\"\x16\n" +
	"\x14getHighestBidRequest\"/\n" +
	"\x15getHighestBidResponse\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\"\x13\n" +
	"\x11getIsEndedRequest\",\n" +
	"\x12getIsEndedResponse\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\bR\x06amount*+\n" +
	"\vmessageType\x12\a\n" +
	"\x03BID\x10\x00\x12\b\n" +
	"\x04JOIN\x10\x01\x12\t\n" +
	"\x05LEAVE\x10\x022\xce\x02\n" +
	"\x10ITUAuctionServer\x120\n" +
	"\vjoinBidding\x12\f.joinRequest\x1a\x11.broadcastMessage0\x01\x12+\n" +
	"\n" +
	"publishBid\x12\v.bidMessage\x1a\x10.publishResponse\x12-\n" +
	"\fleaveBidding\x12\r.leaveRequest\x1a\x0e.leaveResponse\x12>\n" +
	"\rgetHighestBid\x12\x15.getHighestBidRequest\x1a\x16.getHighestBidResponse\x128\n" +
	"\rgetEndAuction\x12\x12.getIsEndedRequest\x1a\x13.getIsEndedResponse\x122\n" +
	"\tReplicate\x12\x11.ReplicateRequest\x1a\x12.ReplicateResponseB\tZ\a./;grpcb\x06proto3"

var (
	file_proto_proto_rawDescOnce sync.Once
	file_proto_proto_rawDescData []byte
)

func file_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)))
	})
	return file_proto_proto_rawDescData
}

var file_proto_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_proto_goTypes = []any{
	(MessageType)(0),              // 0: messageType
	(*ReplicateRequest)(nil),      // 1: ReplicateRequest
	(*ReplicateResponse)(nil),     // 2: ReplicateResponse
	(*JoinRequest)(nil),           // 3: joinRequest
	(*BidMessage)(nil),            // 4: bidMessage
	(*PublishResponse)(nil),       // 5: publishResponse
	(*LeaveRequest)(nil),          // 6: leaveRequest
	(*LeaveResponse)(nil),         // 7: leaveResponse
	(*BroadcastMessage)(nil),      // 8: broadcastMessage
	(*GetHighestBidRequest)(nil),  // 9: getHighestBidRequest
	(*GetHighestBidResponse)(nil), // 10: getHighestBidResponse
	(*GetIsEndedRequest)(nil),     // 11: getIsEndedRequest
	(*GetIsEndedResponse)(nil),    // 12: getIsEndedResponse
}
var file_proto_proto_depIdxs = []int32{
	0,  // 0: broadcastMessage.type:type_name -> messageType
	3,  // 1: ITUAuctionServer.joinBidding:input_type -> joinRequest
	4,  // 2: ITUAuctionServer.publishBid:input_type -> bidMessage
	6,  // 3: ITUAuctionServer.leaveBidding:input_type -> leaveRequest
	9,  // 4: ITUAuctionServer.getHighestBid:input_type -> getHighestBidRequest
	11, // 5: ITUAuctionServer.getEndAuction:input_type -> getIsEndedRequest
	1,  // 6: ITUAuctionServer.Replicate:input_type -> ReplicateRequest
	8,  // 7: ITUAuctionServer.joinBidding:output_type -> broadcastMessage
	5,  // 8: ITUAuctionServer.publishBid:output_type -> publishResponse
	7,  // 9: ITUAuctionServer.leaveBidding:output_type -> leaveResponse
	10, // 10: ITUAuctionServer.getHighestBid:output_type -> getHighestBidResponse
	12, // 11: ITUAuctionServer.getEndAuction:output_type -> getIsEndedResponse
	2,  // 12: ITUAuctionServer.Replicate:output_type -> ReplicateResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_proto_init() }
func file_proto_proto_init() {
	if File_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_depIdxs,
		EnumInfos:         file_proto_proto_enumTypes,
		MessageInfos:      file_proto_proto_msgTypes,
	}.Build()
	File_proto_proto = out.File
	file_proto_proto_goTypes = nil
	file_proto_proto_depIdxs = nil
}
