// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ITUAuctionServer_JoinBidding_FullMethodName   = "/ITUAuctionServer/joinBidding"
	ITUAuctionServer_PublishBid_FullMethodName    = "/ITUAuctionServer/publishBid"
	ITUAuctionServer_LeaveBidding_FullMethodName  = "/ITUAuctionServer/leaveBidding"
	ITUAuctionServer_GetHighestBid_FullMethodName = "/ITUAuctionServer/getHighestBid"
)

// ITUAuctionServerClient is the client API for ITUAuctionServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ITUAuctionServerClient interface {
	// Join the bidding and receive broadcast messages via server-side streaming
	JoinBidding(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BroadcastMessage], error)
	// Publish a bid
	PublishBid(ctx context.Context, in *BidMessage, opts ...grpc.CallOption) (*PublishResponse, error)
	// Leave the bidding
	LeaveBidding(ctx context.Context, in *LeaveRequest, opts ...grpc.CallOption) (*LeaveResponse, error)
	// Get highest bid
	GetHighestBid(ctx context.Context, in *GetHighestBidRequest, opts ...grpc.CallOption) (*GetHighestBidResponse, error)
}

type iTUAuctionServerClient struct {
	cc grpc.ClientConnInterface
}

func NewITUAuctionServerClient(cc grpc.ClientConnInterface) ITUAuctionServerClient {
	return &iTUAuctionServerClient{cc}
}

func (c *iTUAuctionServerClient) JoinBidding(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BroadcastMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ITUAuctionServer_ServiceDesc.Streams[0], ITUAuctionServer_JoinBidding_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[JoinRequest, BroadcastMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ITUAuctionServer_JoinBiddingClient = grpc.ServerStreamingClient[BroadcastMessage]

func (c *iTUAuctionServerClient) PublishBid(ctx context.Context, in *BidMessage, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, ITUAuctionServer_PublishBid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iTUAuctionServerClient) LeaveBidding(ctx context.Context, in *LeaveRequest, opts ...grpc.CallOption) (*LeaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveResponse)
	err := c.cc.Invoke(ctx, ITUAuctionServer_LeaveBidding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iTUAuctionServerClient) GetHighestBid(ctx context.Context, in *GetHighestBidRequest, opts ...grpc.CallOption) (*GetHighestBidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHighestBidResponse)
	err := c.cc.Invoke(ctx, ITUAuctionServer_GetHighestBid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ITUAuctionServerServer is the server API for ITUAuctionServer service.
// All implementations must embed UnimplementedITUAuctionServerServer
// for forward compatibility.
type ITUAuctionServerServer interface {
	// Join the bidding and receive broadcast messages via server-side streaming
	JoinBidding(*JoinRequest, grpc.ServerStreamingServer[BroadcastMessage]) error
	// Publish a bid
	PublishBid(context.Context, *BidMessage) (*PublishResponse, error)
	// Leave the bidding
	LeaveBidding(context.Context, *LeaveRequest) (*LeaveResponse, error)
	// Get highest bid
	GetHighestBid(context.Context, *GetHighestBidRequest) (*GetHighestBidResponse, error)
	mustEmbedUnimplementedITUAuctionServerServer()
}

// UnimplementedITUAuctionServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedITUAuctionServerServer struct{}

func (UnimplementedITUAuctionServerServer) JoinBidding(*JoinRequest, grpc.ServerStreamingServer[BroadcastMessage]) error {
	return status.Errorf(codes.Unimplemented, "method JoinBidding not implemented")
}
func (UnimplementedITUAuctionServerServer) PublishBid(context.Context, *BidMessage) (*PublishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishBid not implemented")
}
func (UnimplementedITUAuctionServerServer) LeaveBidding(context.Context, *LeaveRequest) (*LeaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveBidding not implemented")
}
func (UnimplementedITUAuctionServerServer) GetHighestBid(context.Context, *GetHighestBidRequest) (*GetHighestBidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHighestBid not implemented")
}
func (UnimplementedITUAuctionServerServer) mustEmbedUnimplementedITUAuctionServerServer() {}
func (UnimplementedITUAuctionServerServer) testEmbeddedByValue()                          {}

// UnsafeITUAuctionServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ITUAuctionServerServer will
// result in compilation errors.
type UnsafeITUAuctionServerServer interface {
	mustEmbedUnimplementedITUAuctionServerServer()
}

func RegisterITUAuctionServerServer(s grpc.ServiceRegistrar, srv ITUAuctionServerServer) {
	// If the following call pancis, it indicates UnimplementedITUAuctionServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ITUAuctionServer_ServiceDesc, srv)
}

func _ITUAuctionServer_JoinBidding_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JoinRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ITUAuctionServerServer).JoinBidding(m, &grpc.GenericServerStream[JoinRequest, BroadcastMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ITUAuctionServer_JoinBiddingServer = grpc.ServerStreamingServer[BroadcastMessage]

func _ITUAuctionServer_PublishBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BidMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITUAuctionServerServer).PublishBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ITUAuctionServer_PublishBid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITUAuctionServerServer).PublishBid(ctx, req.(*BidMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ITUAuctionServer_LeaveBidding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITUAuctionServerServer).LeaveBidding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ITUAuctionServer_LeaveBidding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITUAuctionServerServer).LeaveBidding(ctx, req.(*LeaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ITUAuctionServer_GetHighestBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHighestBidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITUAuctionServerServer).GetHighestBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ITUAuctionServer_GetHighestBid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITUAuctionServerServer).GetHighestBid(ctx, req.(*GetHighestBidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ITUAuctionServer_ServiceDesc is the grpc.ServiceDesc for ITUAuctionServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ITUAuctionServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ITUAuctionServer",
	HandlerType: (*ITUAuctionServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "publishBid",
			Handler:    _ITUAuctionServer_PublishBid_Handler,
		},
		{
			MethodName: "leaveBidding",
			Handler:    _ITUAuctionServer_LeaveBidding_Handler,
		},
		{
			MethodName: "getHighestBid",
			Handler:    _ITUAuctionServer_GetHighestBid_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "joinBidding",
			Handler:       _ITUAuctionServer_JoinBidding_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto.proto",
}
