// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: grpc/proto.proto

package grpc

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ITUDatabase_SendRequest_FullMethodName = "/ITUDatabase/sendRequest"
	ITUDatabase_SendReply_FullMethodName   = "/ITUDatabase/sendReply"
	ITUDatabase_SendLeave_FullMethodName   = "/ITUDatabase/sendLeave"
)

// ITUDatabaseClient is the client API for ITUDatabase service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ITUDatabaseClient interface {
	// Request to enter at time T
	SendRequest(ctx context.Context, in *AccessRequest, opts ...grpc.CallOption) (*Confirm, error)
	// Granted permission at time T
	SendReply(ctx context.Context, in *AccessReply, opts ...grpc.CallOption) (*Confirm, error)
	// Exited at time T
	SendLeave(ctx context.Context, in *LeaveNotice, opts ...grpc.CallOption) (*Confirm, error)
}

type iTUDatabaseClient struct {
	cc grpc.ClientConnInterface
}

func NewITUDatabaseClient(cc grpc.ClientConnInterface) ITUDatabaseClient {
	return &iTUDatabaseClient{cc}
}

func (c *iTUDatabaseClient) SendRequest(ctx context.Context, in *AccessRequest, opts ...grpc.CallOption) (*Confirm, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Confirm)
	err := c.cc.Invoke(ctx, ITUDatabase_SendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iTUDatabaseClient) SendReply(ctx context.Context, in *AccessReply, opts ...grpc.CallOption) (*Confirm, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Confirm)
	err := c.cc.Invoke(ctx, ITUDatabase_SendReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iTUDatabaseClient) SendLeave(ctx context.Context, in *LeaveNotice, opts ...grpc.CallOption) (*Confirm, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Confirm)
	err := c.cc.Invoke(ctx, ITUDatabase_SendLeave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ITUDatabaseServer is the server API for ITUDatabase service.
// All implementations must embed UnimplementedITUDatabaseServer
// for forward compatibility.
type ITUDatabaseServer interface {
	// Request to enter at time T
	SendRequest(context.Context, *AccessRequest) (*Confirm, error)
	// Granted permission at time T
	SendReply(context.Context, *AccessReply) (*Confirm, error)
	// Exited at time T
	SendLeave(context.Context, *LeaveNotice) (*Confirm, error)
	mustEmbedUnimplementedITUDatabaseServer()
}

// UnimplementedITUDatabaseServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedITUDatabaseServer struct{}

func (UnimplementedITUDatabaseServer) SendRequest(context.Context, *AccessRequest) (*Confirm, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRequest not implemented")
}
func (UnimplementedITUDatabaseServer) SendReply(context.Context, *AccessReply) (*Confirm, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendReply not implemented")
}
func (UnimplementedITUDatabaseServer) SendLeave(context.Context, *LeaveNotice) (*Confirm, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendLeave not implemented")
}
func (UnimplementedITUDatabaseServer) mustEmbedUnimplementedITUDatabaseServer() {}
func (UnimplementedITUDatabaseServer) testEmbeddedByValue()                     {}

// UnsafeITUDatabaseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ITUDatabaseServer will
// result in compilation errors.
type UnsafeITUDatabaseServer interface {
	mustEmbedUnimplementedITUDatabaseServer()
}

func RegisterITUDatabaseServer(s grpc.ServiceRegistrar, srv ITUDatabaseServer) {
	// If the following call pancis, it indicates UnimplementedITUDatabaseServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ITUDatabase_ServiceDesc, srv)
}

func _ITUDatabase_SendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITUDatabaseServer).SendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ITUDatabase_SendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITUDatabaseServer).SendRequest(ctx, req.(*AccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ITUDatabase_SendReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessReply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITUDatabaseServer).SendReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ITUDatabase_SendReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITUDatabaseServer).SendReply(ctx, req.(*AccessReply))
	}
	return interceptor(ctx, in, info, handler)
}

func _ITUDatabase_SendLeave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveNotice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITUDatabaseServer).SendLeave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ITUDatabase_SendLeave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITUDatabaseServer).SendLeave(ctx, req.(*LeaveNotice))
	}
	return interceptor(ctx, in, info, handler)
}

// ITUDatabase_ServiceDesc is the grpc.ServiceDesc for ITUDatabase service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ITUDatabase_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ITUDatabase",
	HandlerType: (*ITUDatabaseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sendRequest",
			Handler:    _ITUDatabase_SendRequest_Handler,
		},
		{
			MethodName: "sendReply",
			Handler:    _ITUDatabase_SendReply_Handler,
		},
		{
			MethodName: "sendLeave",
			Handler:    _ITUDatabase_SendLeave_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto.proto",
}
