// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type of broadcast message
type MessageType int32

const (
	MessageType_CHAT  MessageType = 0
	MessageType_JOIN  MessageType = 1
	MessageType_LEAVE MessageType = 2
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "CHAT",
		1: "JOIN",
		2: "LEAVE",
	}
	MessageType_value = map[string]int32{
		"CHAT":  0,
		"JOIN":  1,
		"LEAVE": 2,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{0}
}

// Request message when a client joins
type JoinRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ParticipantName string                 `protobuf:"bytes,1,opt,name=participant_name,json=participantName,proto3" json:"participant_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRequest) GetParticipantName() string {
	if x != nil {
		return x.ParticipantName
	}
	return ""
}

// Message for publishing chat content
type ChatMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ParticipantName string                 `protobuf:"bytes,1,opt,name=participant_name,json=participantName,proto3" json:"participant_name,omitempty"`
	Content         string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Lamport         int64                  `protobuf:"varint,3,opt,name=lamport,proto3" json:"lamport,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMessage) GetParticipantName() string {
	if x != nil {
		return x.ParticipantName
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetLamport() int64 {
	if x != nil {
		return x.Lamport
	}
	return 0
}

// Response after publishing a message
type PublishResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	LamportTimestamp int64                  `protobuf:"varint,2,opt,name=lamport_timestamp,json=lamportTimestamp,proto3" json:"lamport_timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{2}
}

func (x *PublishResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublishResponse) GetLamportTimestamp() int64 {
	if x != nil {
		return x.LamportTimestamp
	}
	return 0
}

// Request message when a client leaves
type LeaveRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ParticipantName string                 `protobuf:"bytes,1,opt,name=participant_name,json=participantName,proto3" json:"participant_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LeaveRequest) Reset() {
	*x = LeaveRequest{}
	mi := &file_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRequest) ProtoMessage() {}

func (x *LeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRequest.ProtoReflect.Descriptor instead.
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{3}
}

func (x *LeaveRequest) GetParticipantName() string {
	if x != nil {
		return x.ParticipantName
	}
	return ""
}

// Response after leaving
type LeaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveResponse) Reset() {
	*x = LeaveResponse{}
	mi := &file_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveResponse) ProtoMessage() {}

func (x *LeaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveResponse.ProtoReflect.Descriptor instead.
func (*LeaveResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{4}
}

func (x *LeaveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Broadcast message sent to all clients
type BroadcastMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Content          string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	LamportTimestamp int64                  `protobuf:"varint,2,opt,name=lamport_timestamp,json=lamportTimestamp,proto3" json:"lamport_timestamp,omitempty"`
	Type             MessageType            `protobuf:"varint,3,opt,name=type,proto3,enum=MessageType" json:"type,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BroadcastMessage) Reset() {
	*x = BroadcastMessage{}
	mi := &file_proto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastMessage) ProtoMessage() {}

func (x *BroadcastMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastMessage.ProtoReflect.Descriptor instead.
func (*BroadcastMessage) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{5}
}

func (x *BroadcastMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *BroadcastMessage) GetLamportTimestamp() int64 {
	if x != nil {
		return x.LamportTimestamp
	}
	return 0
}

func (x *BroadcastMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_CHAT
}

var File_proto_proto protoreflect.FileDescriptor

const file_proto_proto_rawDesc = "" +
	"\n" +
	"\vproto.proto\"8\n" +
	"\vjoinRequest\x12)\n" +
	"\x10participant_name\x18\x01 \x01(\tR\x0fparticipantName\"l\n" +
	"\vchatMessage\x12)\n" +
	"\x10participant_name\x18\x01 \x01(\tR\x0fparticipantName\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x18\n" +
	"\alamport\x18\x03 \x01(\x03R\alamport\"X\n" +
	"\x0fpublishResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12+\n" +
	"\x11lamport_timestamp\x18\x02 \x01(\x03R\x10lamportTimestamp\"9\n" +
	"\fleaveRequest\x12)\n" +
	"\x10participant_name\x18\x01 \x01(\tR\x0fparticipantName\")\n" +
	"\rleaveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"{\n" +
	"\x10broadcastMessage\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12+\n" +
	"\x11lamport_timestamp\x18\x02 \x01(\x03R\x10lamportTimestamp\x12 \n" +
	"\x04type\x18\x03 \x01(\x0e2\f.messageTypeR\x04type*,\n" +
	"\vmessageType\x12\b\n" +
	"\x04CHAT\x10\x00\x12\b\n" +
	"\x04JOIN\x10\x01\x12\t\n" +
	"\x05LEAVE\x10\x022\x9a\x01\n" +
	"\vITUDatabase\x12-\n" +
	"\bjoinChat\x12\f.joinRequest\x1a\x11.broadcastMessage0\x01\x120\n" +
	"\x0epublishMessage\x12\f.chatMessage\x1a\x10.publishResponse\x12*\n" +
	"\tleaveChat\x12\r.leaveRequest\x1a\x0e.leaveResponseB\tZ\a./;grpcb\x06proto3"

var (
	file_proto_proto_rawDescOnce sync.Once
	file_proto_proto_rawDescData []byte
)

func file_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)))
	})
	return file_proto_proto_rawDescData
}

var file_proto_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_proto_goTypes = []any{
	(MessageType)(0),         // 0: messageType
	(*JoinRequest)(nil),      // 1: joinRequest
	(*ChatMessage)(nil),      // 2: chatMessage
	(*PublishResponse)(nil),  // 3: publishResponse
	(*LeaveRequest)(nil),     // 4: leaveRequest
	(*LeaveResponse)(nil),    // 5: leaveResponse
	(*BroadcastMessage)(nil), // 6: broadcastMessage
}
var file_proto_proto_depIdxs = []int32{
	0, // 0: broadcastMessage.type:type_name -> messageType
	1, // 1: ITUDatabase.joinChat:input_type -> joinRequest
	2, // 2: ITUDatabase.publishMessage:input_type -> chatMessage
	4, // 3: ITUDatabase.leaveChat:input_type -> leaveRequest
	6, // 4: ITUDatabase.joinChat:output_type -> broadcastMessage
	3, // 5: ITUDatabase.publishMessage:output_type -> publishResponse
	5, // 6: ITUDatabase.leaveChat:output_type -> leaveResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_proto_init() }
func file_proto_proto_init() {
	if File_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_depIdxs,
		EnumInfos:         file_proto_proto_enumTypes,
		MessageInfos:      file_proto_proto_msgTypes,
	}.Build()
	File_proto_proto = out.File
	file_proto_proto_goTypes = nil
	file_proto_proto_depIdxs = nil
}
